#!/bin/bash

tdate=`date +"%m/%d/%Y"`
cdate=`date +"%y%m%d"`
rdir=`pwd`
logdir=`pwd`/changelog
if [ ! -d "$logdir" ]; then
mkdir $logdir
fi
logfile=Changelog.log
logpath="$logdir"/"$logfile"

rm -f "$logpath"

# Read sdate from file
if [ -n "$1" ]; then
    sdate=$1
elif [ -f "$logdir/last_log_date" ]; then
    sdate=`cat $logdir/last_log_date`
else
    echo ""
    echo "----------------------- ATTENTION: Start date not defined -----------------------"
    echo ""
    echo "             >>> Please define a start date in mm/dd/yyyy format <<<             "
    echo ""
    echo "---------------------------------------------------------------------------------"
    echo "please input start date:"
    read idate
    if [ "$idate" == "" ];then
        exit
    fi
    sdate=$idate
fi
echo $sdate > "$logdir/last_log_date"

echo "RemixPA Changelog for $sdate" - "$tdate"
echo "---------------------------------------------------------------"
cd $rdir
# Log starter
echo "RemixPA Changelog from $sdate" - "$tdate" >> "$logpath"
echo "---------------------------------------------------------------" >> "$logpath"
echo "" >> "$logpath"
find -name .git | sed 's/\/.git//g' | sed 'N;$!P;$!D;$d' | while read line
do
cd $line
    # Test to see if the repo needs to have a changelog written.
    log=$(git log --pretty="%an - %s" --no-merges --since=$sdate --date-order)
    # Forgive my bad script :P
    project=${line#*/}
    if [ ! -z "$log" ]; then
        if [ ! "$project" == ".repo/manifests" ] && [ ! "$project" == "changelog" ] ;then
        # Write the changelog
        echo " >>> Changelog is updated and written for $project ..."
        echo "Project: $project" >> "$logpath"
        echo "$log" | while read line
        do
        echo " $line" >> "$logpath"
        done
        echo "" >> "$logpath"
        fi
    fi
cd $rdir
done
count=`grep -c "" "$logpath"`
if [ "$count" == "3" ]; then
    echo "No changes, maybe we delayed commit." >> "$logpath"
    echo "" >> "$logpath"
fi
echo "---------------------------------------------------------------" >> "$logpath"
echo "You can see more changelog from http://github.com/RemixPA/Changelog" >> "$logpath"
echo ""
echo "---------------------------------------------------------------"
echo ""
cat $logpath
echo ""
echo "Ready to upload?[y]/[n]"
read answer
if [ "$answer" == "y" ];then
    cd $logdir
    git add .
    git commit -am "Changelog: $sdate to $tdate"
    pushme
fi
