#!/bin/bash
#
# Copyright (C) 2013 The MoKee OpenSource Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ -z "$1" ];then
    echo "please input an argument for ota"
    exit 1
fi

if [ ! -e "mk" ];then
    echo "please run me on android top directory!"
    exit 1
fi

DEVICE=$1
BASEDIR=`pwd`

if [ -z "$OUT_DIR" ];then
	OTA_INPUT=out/target/OTA_INPUT/$DEVICE
else
	OTA_INPUT=$OUT_DIR/target/OTA_INPUT/$DEVICE
fi

mkdir -p $OTA_INPUT

if [ -z "`which bsdiff 2> /dev/null`" ];then
        echo "Please do lunch first!"
        exit 1
elif [ -z "$OTA_INPUT" ];then
	echo "OTA_INPUT not defined!"
	exit 1
else
	INPUT=$OTA_INPUT
fi

if [ -z "$OUT_DIR" ];then
	OUTPUT=out/target/OTA/$DEVICE
else
	OUTPUT=$OUT_DIR/target/OTA/$DEVICE
fi

cd $BASEDIR/out/target/product/$DEVICE
for file in $(find pa_$DEVICE-4*.zip -type f -print); do
    cp $file $BASEDIR/$INPUT/$file 2> /dev/null
done
cd $BASEDIR

if [ -f build/tools/mk_ota_script/exclude_check ];then
    . build/tools/mk_ota_script/exclude_check
else
    unset $EXCLUDE_CHECK_MAIN
fi

echo ""
echo "OTA: RemixPA"
build/tools/mk_ota_script/ota $INPUT $OUTPUT
rm -rf $OUTPUT/../tmp

